logger:
  app_name: "forecast"
  level: "debug"
  color: true
  console: true

geometry:
  input_file: "D:/linux/metada/applications/forecast/wrfinput_d01"

state:
  input_file: "D:/linux/metada/applications/forecast/wrfinput_d01"
  timestamp: "2000-01-24T12:00:00Z"
  variables:
    - U
    - V
    - QVAPOR
    - T
    - PH
    - MU
    - MUB
    - P
    - PB
    - T2
    - Q2
    - U10
    - V10

model:
  time_control:
    start_datetime: "2000-01-24T12:00:00Z"
    forecast_length: 24h
    end_datetime: "2000-01-25T12:00:00Z"
    time_step: 360s
    output_history: true
    history_file: "forecast.nc"
    history_frequency: 3600s
  dynamics:
    advection_scheme: "WENO"
    diffusion: 0.0
  physics:
    microphysics: true
    radiation: true
    pbl: true
    lsm: true
