logger:
  app_name: "forecast"
  level: "debug"
  color: true
  console: true

geometry:
  input_file: "D:/macom/glo_1_6/exp/nmefc_macom_csp_grid_d01.nc"

state:
  input_file: "D:/macom/glo_1_6/exp/nmefc_macom_csp_initinal_d01.nc"
  timestamp: "2000-01-24T12:00:00Z"
  variables:
    - u
    - v
    - w
    - t
    - s


model:
  time_control:
    start_datetime: "2000-01-24T12:00:00Z"
    forecast_length: 24h
    end_datetime: "2000-01-25T12:00:00Z"
    time_step: 360s
    output_history: true
    history_file: "forecast.nc"
    history_frequency: 3600s
  dynamics:
    advection_scheme: "WENO"
    diffusion: 0.0
  physics:
    microphysics: true
    radiation: true
    pbl: true
    lsm: true
