logger:
  app_name: "etkf"
  level: "debug"
  color: true
  console: true

# Geometry for the ensemble
geometry:
  x_dim: 36 
  y_dim: 18

# Ensemble variables to analyze
ensemble:
  variables: "simple"
  members:
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_1.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_2.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_3.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_4.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_5.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_6.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_7.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_8.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_9.txt"

# Observation settings
observations:
  max_distance: 1000.0  # km
  error_threshold: 3.0  # standard deviations
  types:
    - satellite
    - radiosonde
    - surface

# Output settings
output:
  format: netcdf4
  compression_level: 4
  save_ensemble: true
  save_analysis_error: true 