logger:
  app_name: "etkf"
  level: "debug"
  color: true
  console: true

# Geometry for the ensemble
geometry:
  x_dim: 36 
  y_dim: 18

# Ensemble variables to analyze
ensemble:
  - file: D:\linux\pdaf-fork\tutorial\inputs_offline\ens_1.txt
    variables:
      - simple
  - file: D:\linux\pdaf-fork\tutorial\inputs_offline\ens_2.txt
    variables:
      - simple
  - file: D:\linux\pdaf-fork\tutorial\inputs_offline\ens_3.txt
    variables:
      - simple
  - file: D:\linux\pdaf-fork\tutorial\inputs_offline\ens_4.txt
    variables:
      - simple
  - file: D:\linux\pdaf-fork\tutorial\inputs_offline\ens_5.txt
    variables:
      - simple
  - file: D:\linux\pdaf-fork\tutorial\inputs_offline\ens_6.txt
    variables:
      - simple
  - file: D:\linux\pdaf-fork\tutorial\inputs_offline\ens_7.txt
    variables:
      - simple
  - file: D:\linux\pdaf-fork\tutorial\inputs_offline\ens_8.txt
    variables:
      - simple
  - file: D:\linux\pdaf-fork\tutorial\inputs_offline\ens_9.txt
    variables:
      - simple

# Observation settings
observations:
  max_distance: 1000.0  # km
  error_threshold: 3.0  # standard deviations
  types:
    - satellite
    - radiosonde
    - surface

# Output settings
output:
  format: netcdf4
  compression_level: 4
  save_ensemble: true
  save_analysis_error: true 