logger:
  app_name: "etkf"
  level: "debug"
  color: true
  console: true

# Geometry for the ensemble
geometry:
  x_dim: 36
  y_dim: 18

# Ensemble variables to analyze
ensemble:
  variables: "simple"
  members:
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_1.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_2.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_3.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_4.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_5.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_6.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_7.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_8.txt"
    - state:
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/ens_9.txt"

# Observation settings
observations:
  types:
    - obs_A:
        if_use: true
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/obs.txt"
        variables:
          - simple:
              if_use: true
              error: 0.1  # standard deviations
              missing_value: -999.0
    - obs_B:
        if_use: false
        file: "D:/linux/pdaf-fork/tutorial/inputs_offline/obs_B.txt"
        variables:
          - simple:
              if_use: true
              error: 0.1  # standard deviations
              missing_value: -999.0

# Output settings
output:
  format: netcdf4
  compression_level: 4
  save_ensemble: true
  save_analysis_error: true 