logger:
  app_name: "etkf"
  level: "debug"
  color: true
  console: true

# Ensemble parameters
ensemble_size: 9
inflation_factor: 1.0
localization_radius: 500.0  # km

# Geometry
geometry:
  x_dim: 36 
  y_dim: 18

# State variables to analyze
state:
  file: D:\linux\pdaf-fork\tutorial\inputs_offline\ens_1.txt
  variables:
    - simple

# Observation settings
observations:
  max_distance: 1000.0  # km
  error_threshold: 3.0  # standard deviations
  types:
    - satellite
    - radiosonde
    - surface

# Computational settings
compute:
  num_threads: 8
  batch_size: 1000
  use_gpu: true

# Output settings
output:
  format: netcdf4
  compression_level: 4
  save_ensemble: true
  save_analysis_error: true 